command_timeout = 600000
format = """
$time$dotnet$nodejs$python$docker_context$directory$git_branch$git_status$git_state
$cmd_duration$character"""

[time]
disabled = false
format = '[\[$time\]]($style) '
style = "bright-black"
time_format = "%H:%M:%S"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[V](bold yellow)"

[directory]
style = "cyan"
truncate_to_repo = true
truncation_length = 3

[git_branch]
symbol = " "
style = "purple"

[git_status]
style = "red"
format = '([\[$all_status$ahead_behind\]]($style))'
disabled = true  # Disabled to avoid slowdowns on large repos

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_commit]
commit_hash_length = 7
format = "[$hash]($style) "
style = "green"

[dotnet]
symbol = " "  # Lambda symbol
style = "blue"
heuristic = true

[nodejs]
symbol = " "
style = "green"
detect_files = ["package.json", ".nvmrc"]
detect_folders = ["node_modules"]

[python]
symbol = " "
style = "yellow"
detect_extensions = ["py"]
detect_files = ["requirements.txt", ".python-version", "pyproject.toml", "Pipfile"]

[docker_context]
symbol = " "
style = "blue"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "yellow"

[memory_usage]
disabled = false
threshold = 70
format = "ram [$ram]($style) "
style = "dimmed red"

[package]
symbol = "📦 "
style = "red"
disabled = false

[username]
show_always = false
format = "[$user]($style)@"
style_user = "green bold"
style_root = "red bold"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "green dimmed"
